- hosts: localhost
  vars:
    TERRAFORM_VERSION: 1.7.4
    local_bin_path: "{{ lookup('env', 'HOME') }}/.local/bin"
    terraform_url_base: "https://releases.hashicorp.com/terraform/{{ TERRAFORM_VERSION }}/terraform_{{ TERRAFORM_VERSION }}_{{ ansible_system | lower }}_amd64.zip"
    terraform_dest: "{{ local_bin_path }}/terraform_{{ TERRAFORM_VERSION }}.zip"
  tasks:
    - name: Install necessary packages
      package:
        name: "{{ item }}"
        state: present
      loop:
        - unzip
        # Add other packages here if needed
      become: yes

    - name: Create ~/.local/bin directory
      file:
        path: "{{ local_bin_path }}"
        state: directory

    - name: Download Terraform binary
      get_url:
        url: "{{ terraform_url_base }}"
        dest: "{{ terraform_dest }}"
      when: ansible_system | lower in ['linux', 'darwin']

    - name: Unzip Terraform binary
      unarchive:
        src: "{{ terraform_dest }}"
        dest: "{{ local_bin_path }}"
        remote_src: yes
      when: ansible_system | lower in ['linux', 'darwin']

